In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from keras.layers import *
from keras.models import *
from keras.utils import *
from sklearn.preprocessing import *
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
import random
import re

Using TensorFlow backend.


In [2]:
file = 'the_last_of_us.txt'

text = ''
array = []
with open(file, encoding="utf-8") as f:
    lines = f.readlines()
    
    text = text.join([l for l in lines if re.match(r'^[A-Z].*:', l)]) #정규식 표현에 맞는 것을 가져오는 것으로 
    #시작이 [A-Z] 에 있고 : 뒤에 있는 것까지 가져오는 것 한마디로 대사 부분만 가져오는 것
    
for t in text.split('\n')[:1000]: #개행문자로 라인을 나눠주는것
    array.append(t) #array에 배열로 추가해줌

array

["Joel: Tommy, I-...Tommy. Tommy, listen to me. He's the contractor, okay? I",
 'Sarah: Hey.',
 'Joel: Scoot.',
 'Sarah: Fun day at work, huh?',
 "Joel: What are you still doing up? It's late.",
 'Sarah: Oh crud. What time is it?',
 "Joel: It's way past your bedtime.",
 "Sarah: But it's still today.",
 'Joel: Honey, please not right now. I do not have the energy for this.',
 'Sarah: Here.',
 "Joel: What's this?",
 'Sarah: Your birthday.',
 'Sarah: You kept complaining about your broken watch... So I figured, you know.',
 'Joel: Honey, this is...',
 'Sarah: What?',
 "Joel: It's nice, but I-...I think it's stuck. It's not...",
 'Sarah: What? No, no, no, no.',
 'Sarah: Oh, ha, ha.',
 'Joel: Where did you get the money for this?',
 'Sarah: Drugs. I sell hardcore drugs.',
 'Joel: Oh, good. You can start helping out with the mortgage then.',
 'Sarah: Stsh - yeah, you wish.',
 'Joel: Goodnight, baby girl.',
 'Sarah: Hello?',
 'Tommy: Sarah, honey, I need you to get your daddy on the phone.',


In [3]:
token = Tokenizer(lower=False, filters='.,?;\'\"-')
token.fit_on_texts(array)


In [4]:
token.word_index

{'Joel:': 1,
 'Tess:': 2,
 'I': 3,
 's': 4,
 'the': 5,
 'you': 6,
 'Ellie:': 7,
 'to': 8,
 'it': 9,
 't': 10,
 'we': 11,
 're': 12,
 'a': 13,
 'You': 14,
 'this': 15,
 'that': 16,
 'Sarah:': 17,
 'We': 18,
 'of': 19,
 'here': 20,
 'up': 21,
 'out': 22,
 'on': 23,
 'What': 24,
 'get': 25,
 'is': 26,
 'are': 27,
 'me': 28,
 'Tommy:': 29,
 'Let': 30,
 'your': 31,
 'there': 32,
 'm': 33,
 'do': 34,
 'in': 35,
 'go': 36,
 'Oh': 37,
 'they': 38,
 'for': 39,
 'just': 40,
 'Yeah': 41,
 'us': 42,
 'Marlene:': 43,
 'can': 44,
 'It': 45,
 'They': 46,
 'know': 47,
 'with': 48,
 'what': 49,
 'll': 50,
 'Guard:': 51,
 '2:': 52,
 'No': 53,
 'and': 54,
 'Tess': 55,
 'was': 56,
 'gonna': 57,
 'Hey': 58,
 'not': 59,
 'be': 60,
 'How': 61,
 'Joel': 62,
 'way': 63,
 'back': 64,
 'Alright': 65,
 'There': 66,
 'got': 67,
 'see': 68,
 'That': 69,
 'mon': 70,
 'around': 71,
 'don': 72,
 'C': 73,
 'shit': 74,
 'through': 75,
 'This': 76,
 'all': 77,
 'Okay': 78,
 'Look': 79,
 'have': 80,
 'Get': 81,
 'hell': 8

In [5]:
len(token.word_index)

1384

In [6]:
seq = token.texts_to_sequences(array)
seq

#(sample, timestep, feature)
# I am student

[[1, 130, 3, 130, 130, 626, 8, 28, 103, 4, 5, 627, 104, 3],
 [17, 58],
 [1, 628],
 [17, 629, 330, 111, 266, 331],
 [1, 24, 27, 6, 112, 193, 21, 45, 4, 630],
 [17, 37, 631, 24, 137, 26, 9],
 [1, 45, 4, 63, 430, 31, 632],
 [17, 221, 9, 4, 112, 222],
 [1, 332, 431, 59, 92, 88, 3, 34, 59, 80, 5, 633, 39, 15],
 [17, 183],
 [1, 24, 4, 15],
 [17, 333, 634],
 [17, 14, 635, 636, 99, 31, 334, 165, 138, 3, 637, 6, 47],
 [1, 332, 15, 26],
 [17, 24],
 [1, 45, 4, 638, 166, 3, 3, 100, 9, 4, 639, 45, 4, 59],
 [17, 24, 53, 105, 105, 105],
 [17, 37, 432, 432],
 [1, 113, 139, 6, 25, 5, 640, 39, 15],
 [17, 641, 3, 433, 642, 643],
 [1, 37, 114, 14, 44, 644, 645, 22, 48, 5, 646, 223],
 [17, 647, 335, 6, 648],
 [1, 649, 115, 336],
 [17, 337],
 [29, 194, 434, 3, 89, 6, 8, 25, 31, 650, 23, 5, 435],
 [17, 267, 130, 49, 137, 26, 9],
 [29, 3, 89, 8, 338, 8, 31, 651, 88, 66, 4, 156],
 [17, 267, 130, 337],
 [17, 24, 56, 16, 77, 99, 184, 224, 14, 35, 20],
 [268, 45, 652, 16, 49, 11, 653, 654, 269, 655, 656, 8, 60],


In [7]:
seq = pad_sequences(seq, maxlen=10)
seq

array([[ 130,  626,    8, ...,  627,  104,    3],
       [   0,    0,    0, ...,    0,   17,   58],
       [   0,    0,    0, ...,    0,    1,  628],
       ...,
       [  57, 1382,   22, ...,   21,   55,  418],
       [   0,    0,    0, ...,    0,    7,  328],
       [   0,    0,    0, ...,    1, 1384,    9]])

In [8]:
X = seq

In [9]:
Y = np.vstack((X[1:], X[0])) # Y값은 X의 다음 문장을 보고 학습한다했으니 배열을 위로 땡겨오는 작업
Y

array([[   0,    0,    0, ...,    0,   17,   58],
       [   0,    0,    0, ...,    0,    1,  628],
       [   0,    0,    0, ...,  111,  266,  331],
       ...,
       [   0,    0,    0, ...,    0,    7,  328],
       [   0,    0,    0, ...,    1, 1384,    9],
       [ 130,  626,    8, ...,  627,  104,    3]])

In [10]:
Y.shape

(1000, 10)

In [11]:
X = X.reshape(-1, 10, 1)
Y = Y.reshape(-1, 10, 1)
X

array([[[ 130],
        [ 626],
        [   8],
        ...,
        [ 627],
        [ 104],
        [   3]],

       [[   0],
        [   0],
        [   0],
        ...,
        [   0],
        [  17],
        [  58]],

       [[   0],
        [   0],
        [   0],
        ...,
        [   0],
        [   1],
        [ 628]],

       ...,

       [[  57],
        [1382],
        [  22],
        ...,
        [  21],
        [  55],
        [ 418]],

       [[   0],
        [   0],
        [   0],
        ...,
        [   0],
        [   7],
        [ 328]],

       [[   0],
        [   0],
        [   0],
        ...,
        [   1],
        [1384],
        [   9]]])

In [12]:
X.shape

(1000, 10, 1)

In [13]:
Y = to_categorical(Y)
Y

array([[[1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        ...,
        [1., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        ...,
        [1., 0., 0., ..., 0., 0., 0.],
        [0., 1., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        ...,
        [1., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

In [14]:
Y.shape

(1000, 10, 1385)

In [15]:
'''
Bidirectional은 양방향
-> -> -> ->
<- <- <- <-
GRU/LSTM
'''

model = Sequential()
model.add(Bidirectional(SimpleRNN(128, return_sequences=True), input_shape=(10, 1)))
model.add(Bidirectional(SimpleRNN(128, return_sequences=True)))
model.add(Dense(1385, activation='softmax'))
model.summary()
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

W0828 05:45:21.896145 11044 deprecation_wrapper.py:119] From C:\Users\brb11\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0828 05:45:21.908155 11044 deprecation_wrapper.py:119] From C:\Users\brb11\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0828 05:45:21.910157 11044 deprecation_wrapper.py:119] From C:\Users\brb11\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W0828 05:45:22.181536 11044 deprecation_wrapper.py:119] From C:\Users\brb11\Anaconda3\lib\site-packages\keras\optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0828 05:45:22.195674 11044 deprecation_wrapper.py:119] From C:\Users\brb11\Anac

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
bidirectional_1 (Bidirection (None, 10, 256)           33280     
_________________________________________________________________
bidirectional_2 (Bidirection (None, 10, 256)           98560     
_________________________________________________________________
dense_1 (Dense)              (None, 10, 1385)          355945    
Total params: 487,785
Trainable params: 487,785
Non-trainable params: 0
_________________________________________________________________


In [16]:
model.fit(X, Y, epochs=100, batch_size=1)
model.save('model.save')

W0828 05:45:22.283754 11044 deprecation.py:323] From C:\Users\brb11\Anaconda3\lib\site-packages\tensorflow\python\ops\math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
W0828 05:45:22.552006 11044 deprecation_wrapper.py:119] From C:\Users\brb11\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:986: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.



Epoch 1/100
1000/1000 [==============================] - 7s 7ms/step - loss: 5.0172 - acc: 0.3218
Epoch 2/100
1000/1000 [==============================] - 7s 7ms/step - loss: 4.6513 - acc: 0.3270
Epoch 3/100
1000/1000 [==============================] - 7s 7ms/step - loss: 4.4819 - acc: 0.3252
Epoch 4/100
1000/1000 [==============================] - 7s 7ms/step - loss: 4.3290 - acc: 0.3272
Epoch 5/100
1000/1000 [==============================] - 7s 7ms/step - loss: 4.1808 - acc: 0.3249
Epoch 6/100
1000/1000 [==============================] - 7s 7ms/step - loss: 4.0285 - acc: 0.3255
Epoch 7/100
1000/1000 [==============================] - 7s 7ms/step - loss: 3.8942 - acc: 0.3220
Epoch 8/100
1000/1000 [==============================] - 7s 7ms/step - loss: 3.7518 - acc: 0.3232
Epoch 9/100
1000/1000 [==============================] - 7s 7ms/step - loss: 3.6109 - acc: 0.3238
Epoch 10/100
1000/1000 [==============================] - 7s 7ms/step - loss: 3.4626 - acc: 0.3265
Epoch 11/100
1000/1

1000/1000 [==============================] - 7s 7ms/step - loss: 0.9630 - acc: 0.7306
Epoch 84/100
1000/1000 [==============================] - 7s 7ms/step - loss: 0.9997 - acc: 0.7153
Epoch 85/100
1000/1000 [==============================] - 7s 7ms/step - loss: 1.0060 - acc: 0.7174
Epoch 86/100
1000/1000 [==============================] - 7s 7ms/step - loss: 1.0517 - acc: 0.7024
Epoch 87/100
1000/1000 [==============================] - 7s 7ms/step - loss: 0.9992 - acc: 0.7162
Epoch 88/100
1000/1000 [==============================] - 7s 7ms/step - loss: 1.0630 - acc: 0.7009
Epoch 89/100
1000/1000 [==============================] - 7s 7ms/step - loss: 0.9608 - acc: 0.7353
Epoch 90/100
1000/1000 [==============================] - 7s 7ms/step - loss: 0.9535 - acc: 0.7332
Epoch 91/100
1000/1000 [==============================] - 7s 7ms/step - loss: 1.0068 - acc: 0.7116
Epoch 92/100
1000/1000 [==============================] - 7s 7ms/step - loss: 1.0545 - acc: 0.7055
Epoch 93/100
1000/1000 

In [33]:
model = load_model('model.save')

In [34]:
pred = model.predict(X[:1])

pred

array([[[9.41408813e-01, 2.04525597e-04, 2.69441371e-04, ...,
         1.47986311e-12, 1.22063081e-17, 1.16390936e-07],
        [8.26115906e-01, 1.51554272e-02, 9.13145393e-03, ...,
         1.37130706e-11, 1.99095359e-17, 4.28375806e-08],
        [9.92509604e-01, 2.27286705e-06, 7.34543255e-06, ...,
         6.42991113e-14, 2.63277220e-14, 5.58601776e-11],
        ...,
        [7.32515991e-01, 6.77677151e-03, 5.75471204e-04, ...,
         5.57054076e-16, 8.35667744e-13, 5.25532577e-08],
        [1.20294229e-04, 2.83531681e-05, 8.78529590e-06, ...,
         5.84390758e-10, 1.11046719e-12, 4.00861788e-10],
        [1.49202378e-06, 1.68897313e-04, 9.13210351e-06, ...,
         2.85016016e-13, 1.61375904e-12, 1.34881639e-09]]], dtype=float32)

In [35]:
pred = np.argmax(pred, axis=2)
pred

array([[ 0,  0,  0,  0,  0,  3,  0,  0, 17, 58]], dtype=int64)

In [36]:
idx_word = {}
for w in token.word_index:
    idx_word[token.word_index[w]] = w
idx_word

{1: 'Joel:',
 2: 'Tess:',
 3: 'I',
 4: 's',
 5: 'the',
 6: 'you',
 7: 'Ellie:',
 8: 'to',
 9: 'it',
 10: 't',
 11: 'we',
 12: 're',
 13: 'a',
 14: 'You',
 15: 'this',
 16: 'that',
 17: 'Sarah:',
 18: 'We',
 19: 'of',
 20: 'here',
 21: 'up',
 22: 'out',
 23: 'on',
 24: 'What',
 25: 'get',
 26: 'is',
 27: 'are',
 28: 'me',
 29: 'Tommy:',
 30: 'Let',
 31: 'your',
 32: 'there',
 33: 'm',
 34: 'do',
 35: 'in',
 36: 'go',
 37: 'Oh',
 38: 'they',
 39: 'for',
 40: 'just',
 41: 'Yeah',
 42: 'us',
 43: 'Marlene:',
 44: 'can',
 45: 'It',
 46: 'They',
 47: 'know',
 48: 'with',
 49: 'what',
 50: 'll',
 51: 'Guard:',
 52: '2:',
 53: 'No',
 54: 'and',
 55: 'Tess',
 56: 'was',
 57: 'gonna',
 58: 'Hey',
 59: 'not',
 60: 'be',
 61: 'How',
 62: 'Joel',
 63: 'way',
 64: 'back',
 65: 'Alright',
 66: 'There',
 67: 'got',
 68: 'see',
 69: 'That',
 70: 'mon',
 71: 'around',
 72: 'don',
 73: 'C',
 74: 'shit',
 75: 'through',
 76: 'This',
 77: 'all',
 78: 'Okay',
 79: 'Look',
 80: 'have',
 81: 'Get',
 82: 'hell

In [37]:
temp = ''
for l in pred:
    for w in l:
        if w != 0:
            temp += idx_word[w]
            temp += ' '

temp

'I Sarah: Hey '

In [40]:
X[1]

for i in range(10):
    temp = ''
    ran = random.randrange(0, len(X))
    pred = model.predict(np.expand_dims(X[ran], axis=0))
    
    pred = np.argmax(pred, axis=2)
    
    for l in pred:
        for w in l:
            if w != 0:
                temp += idx_word[w]
                temp += ' '
        temp += '\n'
    
    print(array[ran])
    print(temp)

Soldier: Got a couple of civilians in the outer perimeter. Please advise.
Sarah: Daddy what about Uncle Tommy 

Joel: Okay. How do we get out of this place?
Tess: Let s find out So Marlene thinks your immune 

Guard: We'll be done with them soon enough.
Tess: Go go 

Guard 2: Jesus. Well hey, after today this whole Firefly bullshit will be
Ellie: Joel get s the exit 

Tess: Joel, he's right there.
They Robert: Come on 

Sentry 4: Holy shit.
Robert: Shit They cracking down 

Joel: Jesus. Watch it. Watch it.
t don t leave me to turn Please 

Guard: They still haven't found the last two.
Guard 2: I heard one of em was a kid 

Man: Snatched her in the middle of the night. Said she was a Firefly. Can you
Fireflies too loudly You don t want the to 

Robert: Look, they're basically all dead. We can just-- Just go in there,
Tess: That is a stupid idea 

